project:
  type: book
  output-dir: public
  resources:
    - "css/"
    - "js/"
    - "*.html"
    
book:
  title: "Exploring a hilly city"
  author: "Shrividya Ravi @ Te Manatū Waka (Ministy of Transport)"
  chapters:
    - index.qmd
    - hilly_city.qmd
    - network_analysis.qmd
    - walkability.qmd
    - preference.qmd
    - references.qmd

bibliography: references.bib
csl: "ieee.csl"

format:
  html:
    toc: true
    theme: cosmo
    self-contained: true
    number-sections: true
    tbl-cap-location: top
execute:
  echo: false
  warning: false
editor: visual