# Preface {#sec-preface}
Walkability is a subset of quantitative accessibility analyses (which tend to be multi-modal) as well as a framework that underpins people's preference for walking. For example, **the 5C's of walkability**  @londonplanningadvisorycommitteePuttingLondonBack1997 that consider: 

- Convenience
- Conviviality
- Connectedness
- Comfort
- Conspicuousness

Convenience and connectedness include various aspects of the built environment across urban form and transport infrastructure from provision of walking paths to density of amenities and convenience of routes (direct rather than roundabout) etc. Spatial data science is especially relevant here e.g. point pattern analysis (of amenities) and spatial network analysis to better understand the structure of connectivity and potential routes. 

Convenience is also influenced by the natural topography. While most cities of the world have come up and spread along areas of flat and mild gradients, steep streets exist due to nearby hills and mountains. Pronounced examples of predominantly hilly cities include São Paolo, Brazil and Wellington, New Zealand. Unfortunately, walkability analyses typically ignore the impact of street gradients since the majority of large cities are predominantly flat. 

The analysis featured in the following chapters considers _local walkability_ to better understand potential for walking all around the city. The quantitative approaches are described in greater detail in a series of blog posts @raviWalkingWellington2020 @raviWalkingWellingtonWalkability2020 @raviWalkingWellingtonInsights2020 @raviWalkingWellingtonValidation2020 and in Jupyter notebooks on Github @shrivShrivAccessibilityseries2019. This web book is a high level collation of the above resources with a couple of minor additions summarising street slopes of the city (@sec-hilly-city) and walking preference (@sec-preference). 

@sec-hilly-city describes the topographical challenge for Wellington walkers - especially those in suburbs. @sec-network-analysis outlines how network routing output can be used to better represent real world walking times. @sec-walkability uses network routing to analyse a simple case of local walkability questioning whether the walk _to_ the park is as easy as a walk _in_ the park? @sec-preference routes walking trips from the national travel survey and compares where people actually walk in terms of street gradients.  